[variables]
NIXPACKS_METADATA = "railway"

[phases.setup]  
nixPkgs = ["nodejs_20", "npm-9_x", "python3", "pkg-config", "cairo", "pango", "libpng", "jpeg", "giflib", "librsvg", "pixman"]

[phases.install]
dependsOn = ["setup"]
cmds = [
  "npm ci --omit=dev --ignore-scripts",
  "npm rebuild sharp --platform=linux --arch=x64",
  "npm cache clean --force"
]

[phases.build]
dependsOn = ["install"]
cmds = [
  "npm run build"
]

[start]
cmd = "npm start"

[variables]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"