name: CI Pipeline
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm --filter client run build
      - run: pnpm run db:push

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - run: pnpm test
      - run: pnpm run e2e

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: pnpm
      - run: pnpm install
      - name: Deploy to Netlify
        run: |
          netlify deploy --prod --dir=client/dist \
            -m "v1.0.0-mvp" \
            --headers "Cache-Control: no-cache" \
            --functions "dist/functions"
      - name: Deploy to Railway
        run: railway up
      - name: Create Git Tag
        run: |
          git tag v1.0.0-mvp
          git push origin v1.0.0-mvp
